[package]
name = "debashc"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "debashc"
path = "src/main.rs"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
logos = "0.13"
thiserror = "1.0"
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["console"] }
console_error_panic_hook = "0.1" 
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"